language: python

python:
  - 2.7
  - 3.5

sudo: true


before_install:
  - echo $TRAVIS_PYTHON_VERSION

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install pytest

  #install condacreate
  - python setup.py install

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run $(which py.test) condacreate --runslow --doctest-modules --verbose; else py.test condacreate --verbose; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage report --show-missing; pip install coveralls ; coveralls ; fi

notifications:
  email: false
